services:
  - type: web
    name: aqlli-jurnalist
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: DATABASE_URL
        sync: false